/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Mtbdd */

#ifndef _Included_Mtbdd
#define _Included_Mtbdd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Mtbdd
 * Method:    affiche
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Mtbdd_affiche
  (JNIEnv *, jobject);

/*
 * Class:     Mtbdd
 * Method:    initialisation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Mtbdd_initialisation
  (JNIEnv *, jobject);

/*
 * Class:     Mtbdd
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Mtbdd_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
